### PR TITLE
[WIP] remove docker-deps since we no longer support deps

### PR DESCRIPTION
**Pull request by akashshinde**
Need to remove `docker-deps` since we no longer supporting deps

### CODE REVIEW

**Comment by sbose78** [comment]
test

**Review by kwk — CHANGES_REQUESTED** [review]
No

**Review by tinakurian — APPROVED** [review]

**Comment by sbose78** [comment]
@kwk , A soft migration ( have both dep and mod ) is usually a nice way of doing things. 
In this case, given that the impact is low, do you want to have it supported with `dep` so that it works with golang < 1.11 ?

**Comment by kwk** [comment]
Please give a reason for why we don’t want to support it?

**Comment by kwk** [comment]
@sbose78 I simply don’t want to switch between go versions for our different projects

**Comment by sbose78** [comment]
> Please give a reason for why we don’t want to support it?

- Support only one way of building the code.

However, I do realize that since we are not moving over everything to 1.11 , a soft migration is a good thing. @akashshinde could you please retain support for `dep` in the meantime.

> @sbose78 I simply don’t want to switch between go versions for our different projects

That's a fair argument, @kwk .

**Comment by akashshinde** [comment]
Closing this PR since we have decided to keep support for `dep` as well as `gomod`.

**Pull request closed without merging**
