### PR TITLE
Metrics port should differ from Server port

### PR DESCRIPTION
**Pull request by corinnekrych**
fixes https://github.com/fabric8-services/build-tool-detector/issues/17

### CODE REVIEW

**Comment by sbose78** [comment]
Thanks @corinnekrych . Shouldn't it be the same port though? Like https://api.openshift.io/metrics ?

**Comment by corinnekrych** [comment]
@sbose78 looking in here: https://github.com/fabric8-services/fabric8-wit/blob/master/main.go#L471 it's different port, otherwise you hit "address already in use" issue

**Comment by sbose78** [comment]
That looks like the same port - maybe a bug in the code?

**Comment by corinnekrych** [comment]
@sbose78 by configuration we can explicitly set them as being the same, then the first part of the if applied and we just add a handle. I've added an config for metrics.

The issue in the code was when the 2 ports were different because one of then being not defined. In that case we should start on different ports. taking the metric port (defaulted to 0) will make the metrics server start on self-assigned port.

**Comment by sbose78** [comment]
@tinakurian please ensure you have this covered in your PR with configuration refactoring.

**Pull request merged**
